<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SOAPService"
     targetNamespace="http://oracle.com/sca/soapservice/Enumartiontest/Project1/SOAPService"
     xmlns:tns="http://oracle.com/sca/soapservice/Enumartiontest/Project1/SOAPService"
     xmlns:inp1="http://www.example.org"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../SCA-INF/ENN.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:car"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp1:car"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
