<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://www.example.org"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/CloudIntegration/Coherence+Adapter/dbReference"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/coherence/CloudIntegration/Coherence+Adapter/coherenceReference"
                xmlns:imp2="http://xmlns.oracle.com/pcbpel/adapter/coherence/coherenceReference/response">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/dbReference.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CoherenceCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/coherenceReference.wsdl"/>
        <oracle-xsl-mapper:rootElement name="productDetails" namespace="http://www.example.org"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 16 15:49:06 IST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:productDetails>
      <tns:order_Id>
        <xsl:value-of select="/ns0:CoherenceCollection/ns0:Coherence/ns0:orderid"/>
      </tns:order_Id>
      <tns:cc_Id>
        <xsl:value-of select="/ns0:CoherenceCollection/ns0:Coherence/ns0:ccid"/>
      </tns:cc_Id>
      <tns:cust_Id>
        <xsl:value-of select="/ns0:CoherenceCollection/ns0:Coherence/ns0:customid"/>
      </tns:cust_Id>
      <tns:item_info>
        <tns:name>
          <xsl:value-of select="/ns0:CoherenceCollection/ns0:Coherence/ns0:itemName"/>
        </tns:name>
        <tns:cost>
          <xsl:value-of select="/ns0:CoherenceCollection/ns0:Coherence/ns0:itemCost"/>
        </tns:cost>
      </tns:item_info>
    </tns:productDetails>
  </xsl:template>
</xsl:stylesheet>
